import 'dotenv/config';

export const DATABASE_URL = process.env.DATABASE_URL;
export const REDIS_URL = process.env.REDIS_URL;
export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;

export const ELASTIC_SEARCH_URL = process.env.ELASTIC_SEARCH_URL;
export const ELASTIC_SEARCH_USERNAME = process.env.ELASTIC_SEARCH_USERNAME;
export const ELASTIC_SEARCH_PASSWORD = process.env.ELASTIC_SEARCH_PASSWORD;

console.log(
  '\n',
  {
    DATABASE_URL: DATABASE_URL,
    REDIS_URL: REDIS_URL,

    ACCESS_TOKEN_SECRET: ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET: REFRESH_TOKEN_SECRET,

    GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,

    ELASTIC_SEARCH_URL: ELASTIC_SEARCH_URL,
    ELASTIC_SEARCH_USERNAME: ELASTIC_SEARCH_USERNAME,
    ELASTIC_SEARCH_PASSWORD: ELASTIC_SEARCH_PASSWORD,
  },
  '\n',
);
